name: smashtastic_cricket
description: A cricket game built with Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.8.0
  shared_preferences: ^2.2.0
  google_play_games: ^0.0.2
  in_app_purchase: ^3.1.11
  google_mobile_ads: ^4.0.0
  audioplayers: ^5.2.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/sprites/
    - assets/audio/ 